* Makefile:     + autodetect Linux platforms.     + delete "etw" and "etw.exe" upon make clean.   * Makefile.linux:     + fix compilation on newer Linux systems who no longer use gtk-config and       pkg-config but the more generic pkg-config.     + exit with an error if the required libraries are not available.

diff --git a/trunk/etw/Makefile b/trunk/etw/Makefile
--- a/trunk/etw/Makefile
+++ b/trunk/etw/Makefile
@@ -16,10 +16,18 @@ OBJECTS = highdirent.o	  cpu.o		   human.o	  myiff.o	specials.o \
 .c.o: etw.h menu.h
 	$(CC) $(CFLAGS) $(DEFINES) -c $<
 
-
-etw: *.c
-	@echo "Usa il makefile per la piattaforma apposita!"
-#	$(CC) -o ../etw $(OBJECTS) $(LFLAGS)
+all etw:
+	@case "`uname -s 2>/dev/null`" in \
+	  "Linux") \
+	    $(MAKE) -f Makefile.linux $@ \
+	    ;; \
+	  *) \
+	    echo "Error: please use the makefile for your platform:" \
+	    exit 1 \
+	    ;; \
+	esac
 
 clean:
-	rm -rf *.o
+	rm -rf etw etw.exe *.o
+
+.FORCE:
